//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string address { get; set; }
        public string password { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
